apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    orgId: 1
    uid: timescaledb
    url: timescaledb:5432
    user: cryptiga
    isDefault: true
    editable: false
    jsonData:
      database: cryptiga
      sslmode: disable
      maxOpenConns: 10
      postgresVersion: 1600
      timescaledb: true
    secureJsonData:
      password: cryptiga
